local enemies = {
	{row = 1, shape = 1, health = 2},
	{row = 1, shape = 1, health = 1},
	{row = 1, shape = 1, health = 0},
	{row = 1, shape = 2, health = 2},
	{row = 1, shape = 1, health = 0},
	{row = 1, shape = 1, health = 1},
	{row = 1, shape = 1, health = 2},
	{row = 2, shape = 1, health = 2},
	{row = 2, shape = 2, health = 2},
	{row = 2, shape = 1, health = 1},
	{row = 2, shape = 1, health = 0},
	{row = 2, shape = 1, health = 1},
	{row = 2, shape = 2, health = 2},
	{row = 2, shape = 1, health = 2},
	{row = 3, shape = 1, health = 4},
	{row = 3, shape = 1, health = 4},
	{row = 3, shape = 1, health = 0},
	{row = 3, shape = 1, health = 0},
	{row = 3, shape = 1, health = 0},
	{row = 3, shape = 1, health = 4},
	{row = 3, shape = 1, health = 4},
}

return enemies